export type RequestHeaders = {
  'X-DEVICE-ID'?: string;
  'User-Agent': string;
  'X-Ads-Opt-Out': '1' | '0';
  'X-CM-Bandwidth-KBPS': '-1.000';
  'X-CM-Latency': '-1.000';
  'X-IG-App-Locale': string;
  'X-IG-Device-Locale': string;
  'X-Pigeon-Session-Id': string;
  'X-Pigeon-Rawclienttime': number;
  'X-IG-Connection-Speed': string;
  'X-IG-Bandwidth-Speed-KBPS': '-1.000';
  'X-IG-Bandwidth-TotalBytes-B': '0';
  'X-IG-Bandwidth-TotalTime-MS': '0';
  'X-IG-EU-DC-ENABLED': any;
  'X-IG-Extended-CDN-Thumbnail-Cache-Busting-Value': string;
  'X-Bloks-Version-Id': string;
  'X-MID': string;
  'X-IG-WWW-Claim': string | '0';
  'X-Bloks-Is-Layout-RTL': string;
  'X-IG-Connection-Type': string;
  'X-IG-Capabilities': string;
  'X-IG-App-ID': string;
  'X-IG-Device-ID': string;
  'X-IG-Android-ID': string;
  'Accept-Language': string;
  'X-FB-HTTP-Engine': 'Liger';
  Authorization: undefined | string;
  Host: 'i.instagram.com';
  'Accept-Encoding': 'gzip';
  Connection: 'close';
};
